name: Check Codebase formatting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black[jupyter]
          pip install isort

      - name: Format files
        run: |
          black --config ./pyproject.toml .
          isort .

      - name: Check for changes after formatting
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Warning: Code must be formatted!" >&2
            git status --porcelain
            exit 1
          else
            echo "No formatting issues detected."
          fi
