name: Check Codebase formatting

on:
  pull_request:
  push:
    branches: [main]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black[jupyter] isort ruff

      - name: Run isort
        run: isort --check-only .

      - name: Run black
        run: black --config ./pyproject.toml --check .

      - name: Run ruff
        run: ruff check .
