name: Check Codebase formatting

on:
  pull_request:
  push:
    branches: [main]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black[jupyter]
          pip install isort

      - name: Format files
        run: |
          black --config ./pyproject.toml .
          isort .

      - name: Check for changes after formatting
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Warning: Code must be formatted!" >&2
            git status --porcelain
            exit 1
          else
            echo "No formatting issues detected."
          fi
