name: Release artifacts

on:
  release:
    types: [published]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv

      - name: Build the project with uv
        run: uv build

      - name: List files in dist directory
        run: |
          uv build
          mv ./dist/* ./

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF##*/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${GITHUB_REF##*/v}"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lnas-${{ env.VERSION }}.tar.gz
            lnas-${{ env.VERSION }}-py3-none-any.whl
